# Generated by Django 5.1.3 on 2024-11-13 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('little_lemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_table',
            name='No_of_guests',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='menu_table',
            name='Inventory',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
