# Generated by Django 5.1.3 on 2024-11-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('little_lemon', '0002_alter_booking_table_no_of_guests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_table',
            name='Inventory',
            field=models.SmallIntegerField(),
        ),
    ]
